# Image Input/Output
# ----------------------------------------------------------------------------------------------
height : 512
width : 512
in_channels : 3
num_classes : 2


# Training
# ----------------------------------------------------------------------------------------------
# unet/mod-unet/dncnn/u2net/vnet/unet++
model_name : unet
batch_size : 3
epochs : 30
learning_rate : !!float 3e-4
val_plot_epoch : 2
augment : True
transfer_lr : False
gpu : !!str 0

# Dataset
# ----------------------------------------------------------------------------------------------
patch_size : 256 # height = width, anyone is suitable
dataset_dir : D:/CSML_workPlace/flood_water_ditection_satellite/data/
root_dir : D:/CSML_workPlace/flood_water_ditection_satellite
train_size : 0.8
train_dir : train.csv
valid_dir : valid.csv
test_dir : test.csv

# Logger/Callbacks
# ----------------------------------------------------------------------------------------------
csv : True
val_pred_plot : True
lr : True
tensorboard : True
early_stop : True
checkpoint : True

early_stopping_technique : False
patience : 500 # required for early_stopping, if accuracy does not change for 500 epochs, model will stop automatically

# Evaluation
# ----------------------------------------------------------------------------------------------
load_model_name : epochs_30_07-Mar-22.hdf5
load_model_dir : None


single_image : True # if True, then only index x_test image will plot
index : 29 # by default -1 means random image else specific index image provide by user
