# Image Input/Output
# ----------------------------------------------------------------------------------------------
in_channels : 3
num_classes : 2


# Training
# ----------------------------------------------------------------------------------------------
# unet/mod-unet/dncnn/u2net/vnet/unet++      This our custom models
# sm_unet/sm_linknet/sm_fpn/sm_pspnet                    This models collect from Segmentation Models library
model_name : mnet
batch_size : 2
epochs : 10
learning_rate : !!float 3e-4
val_plot_epoch : 2
augment : True
transfer_lr : False
gpu : !!str 2

# Regular/Cls_balance/Patchify
experiment : regular

# Patchify
# ----------------------------------------------------------------------------------------------
patchify : False
patch_size : 512 # height = width, anyone is suitable
stride : 64
p_train_dir : train_patch.json
p_valid_dir : valid_patch.json
p_test_dir : test_patch.json

# Dataset
# ----------------------------------------------------------------------------------------------
weights : False
balance_weights : [1.4, 8.6]
dataset_dir : D:/CSML_workPlace/flood_water_ditection_satellite/data/
root_dir : D:/CSML_workPlace/flood_water_ditection_satellite
train_size : 0.8
train_dir : train.csv
valid_dir : valid.csv
test_dir : test.csv

# Logger/Callbacks
# ----------------------------------------------------------------------------------------------
csv : True
val_pred_plot : True
lr : True
tensorboard : True
early_stop : True
checkpoint : True
patience : 300 # required for early_stopping, if accuracy does not change for 500 epochs, model will stop automatically

# Evaluation
# ----------------------------------------------------------------------------------------------
load_model_name : mnet_epochs_30_07-Mar-22.hdf5
load_model_dir : None


single_image : True # if True, then only index x_test image will plot
index : -1 # by default -1 means random image else specific index image provide by user
