# Image Input/Output
# ----------------------------------------------------------------------------------------------
height : 256
width : 256
in_channels : 3
num_classes : 2


# Training
# ----------------------------------------------------------------------------------------------
# unet/mod-unet/dncnn/u2net/vnet/unet++
model_name : mnet
batch_size : 3
epochs : 5000
learning_rate : !!float 3e-4
val_plot_epoch : 20
augment : True
transfer_lr : False
gpu : !!str 3


# Patchify
# ----------------------------------------------------------------------------------------------
patchify : True
patch_size : 256 # height = width, anyone is suitable
stride : 64
p_train_dir : train_patch.csv
p_valid_dir : valid_patch.csv
p_test_dir : test_patch.csv

# Dataset
# ----------------------------------------------------------------------------------------------
dataset_dir : /home/mdsamiul/github_project/flood_water_mapping_segmentation/data/
root_dir : /home/mdsamiul/github_project/flood_water_mapping_segmentation
train_size : 0.8
train_dir : train.csv
valid_dir : valid.csv
test_dir : test.csv

# Logger/Callbacks
# ----------------------------------------------------------------------------------------------
csv : True
val_pred_plot : True
lr : True
tensorboard : True
early_stop : True
checkpoint : True

early_stopping_technique : False
patience : 500 # required for early_stopping, if accuracy does not change for 500 epochs, model will stop automatically

# Evaluation
# ----------------------------------------------------------------------------------------------
load_model_name : epochs_30_07-Mar-22.hdf5
load_model_dir : None


single_image : True # if True, then only index x_test image will plot
index : -1 # by default -1 means random image else specific index image provide by user
